fragment PageParts on Page {
  __typename
  title
  description
  hero {
    __typename
    headline
    subheadline
    image
  }
  services {
    __typename
    title
    description
    icon
    features
  }
  stats {
    __typename
    value
    suffix
    label
  }
}
